---
title: Vind de kever
hero_image: images/banner.png
description: Maak een spel waarin je op elk niveau een verborgen kever moet vinden
version: 4
listed: true
copyedit: false
last_tested: "2021-02-26"
steps:
  - 
    title: Je gaat maken
  - 
    title: Startscherm
  - 
    title: Eerste niveau
    completion:
      - engaged
  - 
    title: Papegaai afleiding
  - 
    title: Tweede niveau
  - 
    title: Eindscherm
    completion:
      - internal
  - 
    title: Snelle quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Verbeter je spel
  - 
    title: Deel en speel
  - 
    title: Wat kun je verder nog doen?
