title: find-the-bug
hero_image: images/banner.png
description: find-the-bug description
version: 4
listed: false
copyedit: false
last_tested: "2021-02-26"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
