title: Find the bug
hero_image: images/banner.png
description: Create a game where you have to find a hidden bug on each level.
version: 4
listed: false
copyedit: false
last_tested: "2021-02-26"
steps:
  - title: Introduction
  - title: Add a start screen
  - title: Add a first level
  - title: Add a parrot distraction
  - title: Add a second level
  - title: Add an end screen
  - title: Play the game
  - title: Reflection
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: Upgrade your game
  - title: What next?
