---
title: Find the bug
hero_image: images/banner.png
description: Create a game in which you have to find a hidden bug on each level
version: 4
listed: true
copyedit: false
last_tested: "2021-02-26"
steps:
  - title: You will make
  - title: Start screen
  - title: First level
    completion:
      - engaged
  - title: Parrot distraction
  - title: Second level
  - title: End screen
    completion:
      - internal
  - title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Upgrade your game
  - title: Share and play
  - title: What next?
