---
title: バグを探せ
hero_image: images/banner.png
description: 各レベルで隠されたバグを見つけるゲームを作成します
version: 4
listed: true
copyedit: false
last_tested: "2021-02-26"
steps:
  - 
    title: You will make
  - 
    title: スタート画面
  - 
    title: 第1レベル
    completion:
      - engaged
  - 
    title: オウムが気を散らす
  - 
    title: 第2レベル
  - 
    title: 終了画面
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Upgrade your game
  - 
    title: Share and play
  - 
    title: 次は何をしますか？
