---
title: バグを探せ
hero_image: images/banner.png
description: 各レベルに隠れているバグを見つけるゲームを作成する
meta_title: 子どもと十代の若者向けのScratchコーディング プロジェクト | バグを探せ
meta_description: Raspberry Pi Foundationの子どもと十代の若者向けのコーディングプロジェクトでScratchによるコーディングを学びましょう。Scratchのゲームを作成して、各レベルに隠れているバグを見つけます。
pdf: resources/find-the-bug.pdf
version: 4
listed: true
copyedit: false
last_tested: "2021-02-26"
steps:
  - 
    title: はじめに
  - 
    title: スタート画面
  - 
    title: 第1レベル
    completion:
      - engaged
  - 
    title: オウムが気を散らす
  - 
    title: 第2レベル
  - 
    title: 終了画面
    completion:
      - internal
  - 
    title: ふりかえり
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - internal
  - 
    title: ゲームをアップグレードする
  - 
    title: 共有して遊ぶ
