---
title: Chwilio am chwilen
hero_image: images/banner.png
description: Creu gêm lle mae'n rhaid dod o hyd i chwilen gudd ar bob lefel
meta_title: Scratch coding projects for kids and teens | Find the bug
meta_description: Learn to code in Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make a Scratch game and find a hidden bug on each level.
version: 4
listed: true
copyedit: false
last_tested: "2021-02-26"
steps:
  - 
    title: Cyflwyniad
  - 
    title: Sgrin cychwyn
  - 
    title: Lefel gyntaf
    completion:
      - engaged
  - 
    title: Parot i dynnu sylw
  - 
    title: Ail lefel
  - 
    title: Sgrin y diwedd
    completion:
      - internal
  - 
    title: Chwarae'r gêm
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - internal
  - 
    title: Myfyrio
  - 
    title: Uwchraddio dy gêm
  - 
    title: Beth nesaf?
