---
title: Chwilio am chwilen
hero_image: images/banner.png
description: Creu gêm lle mae'n rhaid dod o hyd i chwilen gudd ar bob lefel
version: 4
listed: true
copyedit: false
last_tested: "2021-02-26"
steps:
  - 
    title: Cyflwyniad
  - 
    title: Sgrin cychwyn
  - 
    title: Lefel gyntaf
    completion: engaged
  - 
    title: Parot i dynnu sylw
  - 
    title: Ail lefel
  - 
    title: Sgrin y diwedd
  - 
    title: Chwarae'r gêm
    completion: internal
  - 
    title: Myfyrio
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion: external
  - 
    title: Uwchraddio dy gêm
  - 
    title: Beth nesaf?
