---
title: Encontre o inseto
hero_image: images/banner.png
description: Crie um jogo no qual você terá que encontrar um inseto escondido em cada nível
version: 4
listed: true
copyedit: false
last_tested: "2021-02-26"
steps:
  - 
    title: You will make
  - 
    title: Tela inicial
  - 
    title: Primeiro nível
    completion:
      - engaged
  - 
    title: A distração do papagaio
  - 
    title: Segundo nível
  - 
    title: Tela final
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Upgrade your game
  - 
    title: Share and play
  - 
    title: E agora?
