---
title: Encontre o inseto
hero_image: images/banner.png
description: Crie um jogo no qual você terá que encontrar um inseto escondido em cada nível
meta_title: Projetos de programação Scratch para crianças e adolescentes | Encontre o Inseto
meta_description: Aprenda a programar no Scratch com os projetos de codificação da Raspberry Pi Foundation para crianças e adolescentes. Faça um jogo Scratch e encontre um inseto escondido em cada nível.
pdf: resources/find-the-bug.pdf
version: 4
listed: true
copyedit: false
last_tested: "2021-02-26"
steps:
  - 
    title: Introdução
  - 
    title: Tela inicial
  - 
    title: Primeiro nível
    completion:
      - engaged
  - 
    title: A distração do papagaio
  - 
    title: Segundo nível
  - 
    title: Tela final
    completion:
      - internal
  - 
    title: Teste rápido
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - internal
  - 
    title: Melhore o seu jogo
  - 
    title: Compartilhe e jogue
