---
title: ದೋಷವನ್ನು ಹುಡುಕಿ
hero_image: images/banner.png
description: ನೀವು ಪ್ರತಿ ಹಂತದಲ್ಲಿ ಗುಪ್ತ ಹುಳವನ್ನು ಕಂಡುಹಿಡಿಯಬೇಕಾದ ಆಟವನ್ನು ರಚಿಸಿ
meta_title: Scratch coding projects for kids and teens | Find the bug
meta_description: Learn to code in Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make a Scratch game and find a hidden bug on each level.
pdf: resources/find-the-bug.pdf
version: 4
listed: true
copyedit: false
last_tested: "2021-02-26"
steps:
  - 
    title: What you will make
  - 
    title: ಪ್ರಾರಂಭದ ಪರದೆ
  - 
    title: ಮೊದಲ ಹಂತ
    completion:
      - engaged
  - 
    title: ಗಿಣಿ ಗಮನಭಂಗ
  - 
    title: ಎರಡನೇ ಹಂತ
  - 
    title: ಅಂತ್ಯ ಪರದೆ
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Upgrade your game
  - 
    title: Share and play
