---
title: Encuentra el insecto
hero_image: images/banner.png
description: Crea un juego en el que tienes que encontrar un insecto oculto en cada nivel
meta_title: Proyectos de codificaci칩n de Scratch para ni침os y adolescentes | Encuentra el insecto
meta_description: Crea un juego en el que tienes que encontrar un insecto oculto en cada nivel.
pdf: resources/find-the-bug.pdf
version: 4
listed: true
copyedit: false
last_tested: "2021-02-26"
steps:
  - 
    title: Lo que har치s
  - 
    title: Pantalla de inicio
  - 
    title: Primer nivel
    completion:
      - engaged
  - 
    title: Loro para distraer
  - 
    title: Segundo nivel
  - 
    title: Pantalla final
    completion:
      - internal
  - 
    title: Examen r치pido
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Mejora tu juego
  - 
    title: Comparte y juega
