---
title: Encuentra el insecto
hero_image: images/banner.png
description: Crea un juego en el que tienes que encontrar un insecto oculto en cada nivel
version: 4
listed: true
copyedit: false
last_tested: "2021-02-26"
steps:
  - 
    title: Introducción
  - 
    title: Pantalla de inicio
  - 
    title: Primer nivel
    completion: engaged
  - 
    title: Loro para distraer
  - 
    title: Segundo nivel
  - 
    title: Pantalla final
  - 
    title: Jugar el juego
    completion: internal
  - 
    title: Reflexión
    completion: external
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - 
    title: Mejora tu juego
  - 
    title: '¿Qué sigue?'
