---
title: Znajdź robaka
hero_image: images/banner.png
description: Stwórz grę, w której na każdym poziomie musisz znaleźć ukrytego robaka
version: 4
listed: true
copyedit: false
last_tested: "2021-02-26"
steps:
  - 
    title: Wprowadzenie
  - 
    title: Ekran startowy
  - 
    title: Pierwszy poziom
    completion: engaged
  - 
    title: Rozpraszająca papuga
  - 
    title: Drugi poziom
  - 
    title: Ekran końcowy
  - 
    title: Zagraj w grę
    completion: internal
  - 
    title: Powtórka
    completion: external
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - 
    title: Ulepsz swoją grę
  - 
    title: Co dalej?
