---
title: Trouver le bug
hero_image: images/banner.png
description: Créer un jeu dans lequel tu dois trouver un bug caché à chaque niveau
version: 4
listed: true
copyedit: false
last_tested: "2021-02-26"
steps:
  - 
    title: Introduction
  - 
    title: Écran de début
  - 
    title: Premier niveau
  - 
    title: Perroquet distraction
  - 
    title: Deuxième niveau
  - 
    title: Écran de fin
  - 
    title: Jouer le jeu
  - 
    title: Réflexion
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - 
    title: Améliorer ton jeu
  - 
    title: Et ensuite ?
