---
title: Trouver le bug
hero_image: images/banner.png
description: Créer un jeu dans lequel tu dois trouver un bug caché à chaque niveau
meta_title: Scratch coding projects for kids and teens | Find the bug
meta_description: Learn to code in Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make a Scratch game and find a hidden bug on each level.
pdf: resources/find-the-bug.pdf
version: 4
listed: true
copyedit: false
last_tested: "2021-02-26"
steps:
  - 
    title: Ce que tu vas faire
  - 
    title: Écran de début
  - 
    title: Premier niveau
    completion:
      - engaged
  - 
    title: Perroquet de distraction
  - 
    title: Deuxième niveau
  - 
    title: Écran de fin
    completion:
      - internal
  - 
    title: Questionnaire rapide
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - internal
  - 
    title: Améliorer ton jeu
  - 
    title: Partager et jouer
