---
title: Trova l'insetto
hero_image: images/banner.png
description: Crea un gioco in cui dovrai trovare l'insetto (bug) nascosto in ogni livello
meta_title: Progetti di programmazione con Scratch per bambini e ragazzi | Trova l'insetto
meta_description: Impara a programmare con Scratch e i progetti di programmazione per bambini e ragazzi offerti dalla Raspberry Pi Foundation. Crea un gioco in Scratch e trova l'insetto (bug) nascosto in ciascun livello.
version: 4
listed: true
copyedit: false
last_tested: "2021-02-26"
steps:
  - 
    title: Quello che farai
  - 
    title: Schermata iniziale
  - 
    title: Primo livello
    completion:
      - engaged
  - 
    title: Il parrot disturbatore
  - 
    title: Secondo livello
  - 
    title: Schermata finale
    completion:
      - internal
  - 
    title: Quiz veloce
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Migliora il tuo gioco
  - 
    title: Condividi e gioca
  - 
    title: E adesso?
